# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44bb1a8eea960730ae1012e2f41a77f867ff30d20026e6e97e119156e012533a6e4be8cdac395b0189bae4e59de327a0e15663f93180ffb38cb2bc9d53c372a1

test:
  secret_key_base: bb46b3f90678ba651381872b7c73997bd0f7f9d2947f4aa4daf1795086df5914b43f1149c0519ba13497fe235fdeeca9853d7e2db49f5f393f438215be47f220

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
